import keyMirror from 'keymirror';

export default keyMirror({
  REQUEST_USER: null,
  REQUEST_USER_SUCCESS: null,
  REQUEST_USER_ERROR: null,

  REQUEST_REPO: null,
  REQUEST_REPO_SUCCESS: null,
  REQUEST_REPO_ERROR: null,

  REQUEST_STARRED_REPOS_PAGE: null,
  REQUEST_STARRED_REPOS_PAGE_SUCCESS: null,
  REQUEST_STARRED_REPOS_PAGE_ERROR: null,

  REQUEST_STARGAZER_PAGE: null,
  REQUEST_STARGAZER_PAGE_SUCCESS: null,
  REQUEST_STARGAZER_PAGE_ERROR: null,

  UPDATE_CREDENTIALS : null,

  LOGIN_REQUEST : null,
  LOGGED_IN_WITH_FB_ERROR : null,
  LOGGED_IN_WITH_FB : null,
  LOGGED_OUT : null,
  
  BROWSE_NEARBY : null,
  SEND_EXCHANGE_REQUEST : null,
  ACCEPT_EXCHANGE_REQUEST : null,
  CANCEL_REQUEST : null,
  ASK_REVIEW : null,
  SEND_MESSAGE : null,

  FOLLOW_USER : null,
  UNFOLLOW_USER : null,

  UPDATE_LIBRARY : null,
  GET_NOTIFICATION_SUCCESS : null,
  GET_NOTIFICATION_ERROR : null,

  GET_FEEDS_SUCCESS : null,
  GET_FEEDS_ERROR : null,

  DELETE_BOOK : null,
  DELETE_ACCOUNT : null,
  DELETE_LIBRARY : null,

  FETCH_BOOKS_FROM_API : null,
  FETCH_BOOKS_FROM_API_SUCCESS : null,
  FETCH_BOOKS_FROM_API_ERROR : null,

  FETCH_NEARBY_BOOKS_FROM_API : null,
  FETCH_NEARBY_BOOKS_FROM_API_SUCCESS : null,
  FETCH_NEARBY_BOOKS_FROM_API_ERROR : null,

  FETCH_BOOK_INFO_FROM_API : null,
  FETCH_BOOK_INFO_FROM_API_SUCCESS : null,
  FETCH_BOOK_INFO_FROM_API_ERROR : null,

  FETCH_GET_BOOK_INFO_FROM_API : null,
  FETCH_GET_BOOK_INFO_FROM_API_SUCCESS : null,

  FETCH_GET_BOOK_INFO_FROM_GOOGLE_API_WITH_ISBN : null,
  FETCH_GET_BOOK_INFO_FROM_GOOGLE_API_WITH_ISBN_SUCCESS : null,
  FETCH_GET_BOOK_INFO_FROM_GOOGLE_API_WITH_ISBN_ERROR : null,

  FETCH_BOOK_UPDATE_FROM_API : null,
  FETCH_BOOK_UPDATE_FROM_API_SUCCESS : null,
  FETCH_BOOK_UPDATE_FROM_API_ERROR : null,
});